### PR TITLE
Update App Colors/Styling

### PR DESCRIPTION
**Pull request by kingo2157**
Changed font and colors.

### CODE REVIEW

**Review by IRHM — COMMENTED** [review]
I'm liking the new colours and the font you've chosen. Looks pretty great overall.

I think it looks better when the Dragger is a darker colour than the Nav though, I tried switching them around and it looked much better.

Look at what it looks like once you switch these and what you might want to change.

Thanks!

**Comment by kingo2157** [comment]
CASTERR_NEW
CASTERR_OLD

**Comment by DanyaalA** [comment]
2nd one is too dark it doesn't blend with the light purple. I think you should keep the 1st one but make it a little darker

**Comment by IRHM** [comment]
> 
> 
> 2nd one is too dark it doesn't blend with the light purple. I think you should keep the 1st one but make it a little darker

Maybe try making the Nav bar and Drag bar a little lighter?

The page and Settings nav bar colors blend pretty well.

**Comment by kingo2157** [comment]
I've got to set the record straight; I have eye-saver mode on, and I have unfortunately based the colour scheme on my perception of these colours.

**Comment by IRHM** [comment]
> 
> 
> I've got to set the record straight; I have eye-saver mode on, and I have unfortunately based the colour scheme on my perception of these colours.

Oh okay, are you still going to change the colors around?

**Comment by IRHM** [comment]
No progress in a while so I'm going to close it. Feel free to come back to this whenever, but at this point it would be better to just create another pr instead of using this one.

**Pull request closed without merging**
