### PR TITLE
Video Player For Watching Past Recordings

### LINKED ISSUE #20: Create a video player so you can watch your recordings.
Possibly as a popup window instead of going to a new page (dont allow popup to close if user clicks out of it because that could cause people to lose their clippings, make them use the 'X' btn).

### PR DESCRIPTION
**Pull request by IRHM**
Create a video player that pops up when user tries to watch a past recording.

Closes #20

### CODE REVIEW

**Comment by IRHM** [comment]
Loading a video from local storage (outside wwwroot folder) is causing the sbond™ Blues.

Chrome console shows this error: Error - Not allowed to load local resource

It is possible to load in the video if it is first converted to a Base64 string, but depending on the file size of the video, this could take a very long time.

**Comment by IRHM** [comment]
Following [this issue](https://github.com/ElectronNET/Electron.NET/issues/449).

**Review by DanyaalA — APPROVED** [review]
Thanks for welcoming me back to caster
In today’s gathering, I would like to focus on all our new volunteers who have joined us since (January 2013, for example).

You have all been chosen to be a part of our association due to a mutual passion for (company’s vision/mission). Your passions help us all to unite and the energy we create is what allows us to achieve our individual as well as group goals. We need you as much as you need us and that why we are grateful to have you join us here at (insert the name of the company).

During the next few months, you will be learning about the different initiatives through our planned activities, seminar, and special events where you will be able to join in and get hands on experiences. I hope these will help you grow to be more productive and smart.

Well, I don’t want to take too much of your time, I need to leave some time for (insert the name of the next person) to introduce himself to all of you and fill you in on some of our up coming activities/projects. Today will be fun and full of learning.

So a very warm welcome to each and every one of you, if youhave nay questions, suggestions, clarifications, or just want to say “hi”, you can find me in the lobby.

**Comment by IRHM** [comment]
> 
> 
> Thanks for welcoming me back to caster
> In today’s gathering, I would like to focus on all our new volunteers who have joined us since (January 2013, for example).
> 
> You have all been chosen to be a part of our association due to a mutual passion for (company’s vision/mission). Your passions help us all to unite and the energy we create is what allows us to achieve our individual as well as group goals. We need you as much as you need us and that why we are grateful to have you join us here at (insert the name of the company).
> 
> During the next few months, you will be learning about the different initiatives through our planned activities, seminar, and special events where you will be able to join in and get hands on experiences. I hope these will help you grow to be more productive and smart.
> 
> Well, I don’t want to take too much of your time, I need to leave some time for (insert the name of the next person) to introduce himself to all of you and fill you in on some of our up coming activities/projects. Today will be fun and full of learning.
> 
> So a very warm welcome to each and every one of you, if youhave nay questions, suggestions, clarifications, or just want to say “hi”, you can find me in the lobby.

I'm removing you from the organization.

**Pull request merged**
